Update caching for CircleCI (#176)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,7 +6,7 @@ commands:
     parameters:
       sbt_version:
         type: string
-        default: "1.3.8"
+        default: "1.3.9"
     steps:
       - run:
           name: Setup SBT
@@ -39,6 +39,63 @@ commands:
                       -print -exec cp {} test-reports \;
           when: always
 
+  update_cache:
+    description: Update cache
+    steps:
+      - save_cache:
+          paths:
+            - ~/sbt
+          key: tooling
+      - save_cache:
+          paths:
+            - ~/.ivy2
+            - ~/.coursier/cache
+            - ~/.sbt
+          key: d-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+
+  publish_snapshots:
+    description: Publish artifacts to Snapshots repository
+    parameters:
+      release_suffix:
+        type: string
+        default: ""
+      play_version:
+        type: string
+        default: ""
+      scala_versions:
+        type: string
+        default: ""
+    steps:
+      - deploy:
+          name: Publish artifacts to Sonatype Snapshots
+          command: |
+                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
+                      echo "Skipped on branch ${CIRCLE_BRANCH}"
+                      exit 0
+                    fi
+                    
+                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
+                    export PUBLISH_REPO_ID="oss.sonatype.org"
+                    export PUBLISH_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
+                    
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
+                    fi
+                    
+                    export RELEASE_SUFFIX="<< parameters.release_suffix >>"
+                    export PLAY_VERSION="<< parameters.play_version >>"
+                    
+                    echo "Publishing artifacts for $PLAY_VERSION"
+                    
+                    if [ "x<< parameters.scala_versions >>" = "x" ]; then
+                      sbt +publish
+                    else
+                      for V in `echo "<< parameters.scala_versions >>"`; do
+                        sbt ++V publish
+                      done
+                    fi
+
 jobs:
   unit_play25:
     docker:
@@ -59,18 +116,12 @@ jobs:
 
       - restore_cache:
           keys:
-          - play25-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
-          - dependencies-
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+          - tooling
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: play25-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
@@ -95,18 +146,12 @@ jobs:
 
       - restore_cache:
           keys:
-          - play26-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
-          - dependencies-
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+          - tooling
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: play26-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
@@ -131,18 +176,12 @@ jobs:
 
       - restore_cache:
           keys:
-          - play27-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
-          - dependencies-
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+          - tooling
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: play27-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
@@ -167,40 +206,70 @@ jobs:
 
       - restore_cache:
           keys:
-          - play28-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
-          - dependencies-
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+          - tooling
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: play28-{{ .Environment.REACTIVEMONGO_SHADED }}-{{ checksum "build.sbt" }}-{{ checksum "project/Common.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
           path: test-reports
 
+  publish_snapshots:
+    docker:
+      - image: circleci/openjdk:8-jdk
+
+    working_directory: ~/repo
+
+    steps:
+      - checkout
+
+      - setup_sbt
+
+      - restore_cache:
+          keys:
+          - tooling
+
+      - publish_snapshots:
+          release_suffix: play25
+          play_version: 2.5.7
+          scala_versions: 2.11.12
+
+      - publish_snapshots:
+          release_suffix: play26
+          play_version: 2.6.7
+          scala_versions: 2.11.12 2.12.10
+
+      - publish_snapshots:
+          release_suffix: play27
+          play_version: 2.7.4
+          scala_versions: 2.11.12 2.12.10 2.13.1
+
+      - publish_snapshots:
+          release_suffix: play28
+          play_version: 2.8.1
+          scala_versions: 2.12.10 2.13.1
+
+      - update_cache
+
 workflows:
   version: 2
 
-  play25:
+  main_suite:
     jobs:
       - unit_play25
-
-  play26:
-    jobs:
       - unit_play26
-
-  play27:
-    jobs:
       - unit_play27
-
-  play28:
-    jobs:
       - unit_play28
-
-# TODO: Snapshot publish on master (nightly schedule?)
+      - publish_snapshots:
+          filters:
+            branches:
+              only:
+                - master
+          requires:
+            - unit_play25
+            - unit_play26
+            - unit_play27
+            - unit_play28
